"""
Django settings for mock_project project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .conf.base import *


if ENVIRONMENT == 'production':
    from .conf.production import *
elif ENVIRONMENT == 'local':
    from .conf.local import *
